# Generated by Django 4.1.7 on 2023-02-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sessiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiondata',
            options={'ordering': ['session', 'key_name']},
        ),
        migrations.RenameField(
            model_name='sessiondata',
            old_name='session_id',
            new_name='session',
        ),
    ]
